-- ENUM
CREATE TYPE status_type AS ENUM (
    'disponible',
    'emprunté'
);


-- AUTEURS
CREATE TABLE authors (
    id_author integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL,
    nationality character varying(30)
);


-- MEMBRES
CREATE TABLE members (
    id_member integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL,
    email character varying(100) NOT NULL UNIQUE,
    phone_number character varying(15) NOT NULL UNIQUE
);


-- LIVRES
CREATE TABLE books (
    id_book integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(100) NOT NULL,
    year smallint,
    status status_type,
    id_author integer NOT NULL,

    CONSTRAINT books_id_author_fkey
        FOREIGN KEY (id_author)
        REFERENCES authors(id_author)
);


-- EMPRUNTS
CREATE TABLE loan (
    id_loan integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_back boolean DEFAULT false,
    expected_return_date date,
    return_date date,
    id_book integer,
    id_member integer,

    CONSTRAINT loan_id_book_fkey
        FOREIGN KEY (id_book)
        REFERENCES books(id_book),

    CONSTRAINT loan_id_member_fkey
        FOREIGN KEY (id_member)
        REFERENCES members(id_member)
);